/**
 * Telnyx WhatsApp incoming message webhook.
 *
 * Configure in Telnyx Portal → Messaging → Profiles → Webhook URL:
 *   https://<your-domain>/api/webhooks/whatsapp
 *
 * Handles text messages only. Responds with an AI reply generated by
 * whatsapp-bot.ts (Claude-powered, La Casa de la Salsa context).
 */

import { NextRequest, NextResponse } from "next/server";
import { getReply } from "@/lib/whatsapp-bot";
import { sendWhatsAppMessage } from "@/lib/whatsapp-send";

interface TelnyxWhatsAppPayload {
  from?: { phone_number?: string };
  to?: { phone_number?: string }[];
  type?: string;
  text?: { body?: string };
}

interface TelnyxWebhookBody {
  data?: {
    event_type?: string;
    payload?: TelnyxWhatsAppPayload;
  };
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: TelnyxWebhookBody;

  try {
    body = (await req.json()) as TelnyxWebhookBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const eventType = body?.data?.event_type;

  // Only handle incoming messages
  if (eventType !== "message.received") {
    return NextResponse.json({ received: true }, { status: 200 });
  }

  const payload = body?.data?.payload;
  const senderPhone = payload?.from?.phone_number;
  const messageType = payload?.type;
  const messageText = payload?.text?.body;

  if (!senderPhone) {
    console.warn("[webhook/whatsapp] Missing sender phone in payload");
    return NextResponse.json({ received: true }, { status: 200 });
  }

  console.log(`[webhook/whatsapp] ${messageType} from ${senderPhone}`);

  // Handle non-text messages gracefully
  if (messageType !== "text" || !messageText) {
    try {
      await sendWhatsAppMessage(
        senderPhone,
        "Hola 👋 Por favor escríbenos un mensaje de texto y con gusto te atendemos."
      );
    } catch (err) {
      console.error("[webhook/whatsapp] Failed to send non-text reply:", err);
    }
    return NextResponse.json({ received: true }, { status: 200 });
  }

  // Generate AI reply and send it
  try {
    const reply = await getReply(senderPhone, messageText);
    await sendWhatsAppMessage(senderPhone, reply);
    console.log(`[webhook/whatsapp] Replied to ${senderPhone}`);
  } catch (err) {
    console.error("[webhook/whatsapp] Failed to generate or send reply:", err);
    // Best-effort fallback
    try {
      await sendWhatsAppMessage(
        senderPhone,
        "Disculpa, tuvimos un problema técnico. Por favor intenta de nuevo en un momento 🙏"
      );
    } catch {
      // ignore fallback error
    }
  }

  return NextResponse.json({ received: true }, { status: 200 });
}
